name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out repo
      uses: actions/checkout@v3

    # Step 2: Set up Python for unit tests (if you have them)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install Dependencies (Flask, etc.)
    - name: Install dependencies
      run: pip install -r requirements.txt

    # Step 4: Run tests (if you have a test suite)
    - name: Run tests
      run: |
        # Example: If you have a 'tests' folder
        # For now, if no tests, just echo a message
        echo "No tests found; skipping test step..."

    # Step 5: Log in to DockerHub using secrets
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Step 6: Build Docker image
    - name: Build the Docker image
      run: |
        docker build -t sillycatlover246/devproject:latest .

    # Step 7: Push Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker push sillycatlover246/devproject:latest
